pub(super) const TOOL_ALIASES: &[(&str, &str)] = &[
    ("inspect_file", "read_downloaded_file"),
    ("search_notifications", "list_recent_notifications"),
    ("search_mail", "list_recent_mail"),
    ("read_file", "read_downloaded_file"),
    ("view_file", "read_downloaded_file"),
    ("view_downloaded_file", "read_downloaded_file"),
    ("view_downloaded", "read_downloaded_file"),
    ("show_file", "read_downloaded_file"),
    ("display_file", "read_downloaded_file"),
    ("get_file", "read_downloaded_file"),
    ("get_file_content", "read_downloaded_file"),
    ("read_file_content", "read_downloaded_file"),
    ("read_downloaded", "read_downloaded_file"),
    ("read_downloaded_files", "read_downloaded_file"),
    ("inspect_downloaded_file", "read_downloaded_file"),
    ("open_file", "open_downloaded_file"),
    ("open_downloaded", "open_downloaded_file"),
    ("open_downloaded_files", "open_downloaded_file"),
    ("list_files", "list_downloaded_files"),
    ("list_downloads", "list_downloaded_files"),
    ("search_downloaded_files", "list_downloaded_files"),
    ("fetch_lms_course_resources", "list_luna_announcements"),
    ("get_lms_course_resources", "list_luna_announcements"),
    ("list_lms_course_resources", "list_luna_announcements"),
    ("fetch_lms_resources", "list_luna_announcements"),
    ("get_lms_resources", "list_luna_announcements"),
    ("list_lms_resources", "list_luna_announcements"),
    ("fetch_luna_course_resources", "list_luna_announcements"),
    ("get_luna_course_resources", "list_luna_announcements"),
    ("list_luna_course_resources", "list_luna_announcements"),
    ("list_course_resources", "list_luna_announcements"),
    ("get_course_resources", "list_luna_announcements"),
    ("get_luna_detail", "get_luna_activity_detail"),
    ("read_luna_activity", "get_luna_activity_detail"),
    ("get_activity_detail", "get_luna_activity_detail"),
    ("download_attachment", "download_luna_attachment"),
    ("download_material", "download_luna_attachment"),
    ("download_file_by_name", "download_course_material"),
    ("download_material_file", "download_course_material"),
    ("download_course_material_file", "download_course_material"),
    ("download_luna_material", "download_course_material"),
    ("download_luna_file", "download_course_material"),
    ("kg_canvas_download_luna_file", "download_course_material"),
    ("browser_reload", "browser_reload_page"),
    ("reload_browser", "browser_reload_page"),
    ("mouse_click", "browser_mouse_click"),
    ("click_at", "browser_mouse_click"),
    ("browser_click_at", "browser_mouse_click"),
    ("mouse_drag", "browser_mouse_drag"),
    ("drag_mouse", "browser_mouse_drag"),
    ("browser_drag", "browser_mouse_drag"),
    ("select_browser_option", "browser_select_option"),
    ("browser_wait", "browser_wait_for"),
    ("wait_for_browser", "browser_wait_for"),
    ("close_browser", "browser_close"),
    ("open_app_page", "open_copilot_page"),
    ("open_copilot", "open_copilot_page"),
    ("calendar_list_events", "list_google_calendar_events"),
    ("calendar_create_event", "create_google_calendar_event"),
    ("calendar_delete_event", "delete_google_calendar_event"),
    ("calendar_update_event", "update_google_calendar_event"),
];

#[cfg(test)]
pub(super) const DISPATCH_TOOL_NAMES: &[&str] = &[
    "list_today_classes",
    "list_week_classes",
    "search_courses",
    "get_course_context",
    "get_course_detail",
    "get_cancellations",
    "get_makeup_classes",
    "get_room_changes",
    "get_exam_timetable",
    "list_luna_todos",
    "get_grades",
    "get_registration",
    "list_syllabus_favorites",
    "list_recent_notifications",
    "get_notification_detail",
    "list_recent_mail",
    "read_mail",
    "list_luna_announcements",
    "get_mail_profile",
    "get_student_profile",
    "get_weather",
    "get_weekly_summary",
    "get_todo_guide",
    "get_upcoming_deadlines",
    "get_luna_activity_detail",
    "refresh_data",
    "list_downloaded_files",
    "read_downloaded_file",
    "write_downloaded_text_file",
    "open_downloaded_file",
    "delete_downloaded_file",
    "download_url",
    "open_luna_attachment",
    "download_luna_attachment",
    "download_course_material",
    "list_browser_windows",
    "open_browser_url",
    "open_copilot_page",
    "read_browser_page",
    "browser_back",
    "browser_forward",
    "browser_reload_page",
    "browser_click",
    "browser_mouse_click",
    "browser_mouse_drag",
    "browser_fill",
    "browser_select_option",
    "browser_press",
    "browser_scroll",
    "browser_wait_for",
    "browser_close",
    "computer_screenshot",
    "computer_mouse_click",
    "computer_mouse_drag",
    "computer_scroll",
    "get_today_brief",
    "create_google_calendar_event",
    "list_google_calendar_events",
    "delete_google_calendar_event",
    "update_google_calendar_event",
];
