use super::schema::{ArgSchema, ToolSpec};

pub(in crate::agent_tools) const TOOL_SPECS: &[ToolSpec] = &[
    ToolSpec {
        name: "list_today_classes",
        category: "授業・時間割",
        signature: "list_today_classes()",
        purpose: "今日の授業一覧",
        schema: ArgSchema::Empty,
    },
    ToolSpec {
        name: "list_week_classes",
        category: "授業・時間割",
        signature: "list_week_classes(offset: 0|1)",
        purpose: "今週または来週の時間割",
        schema: ArgSchema::Int {
            key: "offset",
            max: 1,
        },
    },
    ToolSpec {
        name: "search_courses",
        category: "授業・時間割",
        signature: "search_courses(query: string)",
        purpose: "科目名・科目コード・教員名から候補を探す",
        schema: ArgSchema::Text {
            key: "query",
            max_len: 80,
        },
    },
    ToolSpec {
        name: "get_course_context",
        category: "授業・時間割",
        signature: "get_course_context(query: string)",
        purpose: "科目の時間割・授業計画・教材・Luna活動をまとめて取得",
        schema: ArgSchema::Text {
            key: "query",
            max_len: 80,
        },
    },
    ToolSpec {
        name: "get_course_detail",
        category: "授業・時間割",
        signature: "get_course_detail(kgc_code: string)",
        purpose: "KGC科目コード指定で詳細・授業計画を取得",
        schema: ArgSchema::CourseCode { key: "kgc_code" },
    },
    ToolSpec {
        name: "get_cancellations",
        category: "授業・時間割",
        signature: "get_cancellations()",
        purpose: "休講情報一覧",
        schema: ArgSchema::Empty,
    },
    ToolSpec {
        name: "get_makeup_classes",
        category: "授業・時間割",
        signature: "get_makeup_classes()",
        purpose: "補講情報一覧",
        schema: ArgSchema::Empty,
    },
    ToolSpec {
        name: "get_room_changes",
        category: "授業・時間割",
        signature: "get_room_changes()",
        purpose: "教室変更情報一覧",
        schema: ArgSchema::Empty,
    },
    ToolSpec {
        name: "get_exam_timetable",
        category: "授業・時間割",
        signature: "get_exam_timetable()",
        purpose: "試験時間割",
        schema: ArgSchema::Empty,
    },
    ToolSpec {
        name: "list_luna_todos",
        category: "課題・成績・履修",
        signature: "list_luna_todos()",
        purpose: "Luna の未提出レポート・テスト一覧",
        schema: ArgSchema::Empty,
    },
    ToolSpec {
        name: "get_grades",
        category: "課題・成績・履修",
        signature: "get_grades()",
        purpose: "成績・単位取得状況",
        schema: ArgSchema::Empty,
    },
    ToolSpec {
        name: "get_registration",
        category: "課題・成績・履修",
        signature: "get_registration()",
        purpose: "履修登録科目一覧・単位集計",
        schema: ArgSchema::Empty,
    },
    ToolSpec {
        name: "list_syllabus_favorites",
        category: "課題・成績・履修",
        signature: "list_syllabus_favorites(limit?: number, keyword?: string)",
        purpose: "お気に入りシラバス一覧",
        schema: ArgSchema::LimitKeyword,
    },
    ToolSpec {
        name: "list_recent_notifications",
        category: "お知らせ・メール",
        signature: "list_recent_notifications(limit?: number, keyword?: string)",
        purpose: "最新のお知らせ一覧。keywordを渡すと全お知らせをキーワード検索する",
        schema: ArgSchema::LimitKeyword,
    },
    ToolSpec {
        name: "get_notification_detail",
        category: "お知らせ・メール",
        signature: "get_notification_detail(title: string)",
        purpose: "KWIC/KGC/Lunaのお知らせ本文・送信者・添付を取得(直近の一覧キャッシュから検索)",
        schema: ArgSchema::Text {
            key: "title",
            max_len: 200,
        },
    },
    ToolSpec {
        name: "list_recent_mail",
        category: "お知らせ・メール",
        signature: "list_recent_mail(limit?: number, keyword?: string)",
        purpose: "受信メール一覧。keywordを渡すと件名・本文プレビュー・送信者をキーワード検索する",
        schema: ArgSchema::LimitKeyword,
    },
    ToolSpec {
        name: "read_mail",
        category: "お知らせ・メール",
        signature: "read_mail(message_id: string)",
        purpose: "メール本文",
        schema: ArgSchema::MailMessageId,
    },
    ToolSpec {
        name: "list_luna_announcements",
        category: "お知らせ・メール",
        signature: "list_luna_announcements(limit?: number, keyword?: string)",
        purpose: "Luna科目掲示の一覧(keywordで科目名フィルタ)",
        schema: ArgSchema::LimitKeyword,
    },
    ToolSpec {
        name: "get_mail_profile",
        category: "お知らせ・メール",
        signature: "get_mail_profile()",
        purpose: "メールアカウント情報",
        schema: ArgSchema::Empty,
    },
    ToolSpec {
        name: "get_student_profile",
        category: "学生情報・その他",
        signature: "get_student_profile()",
        purpose: "学籍番号・氏名・学部学科など",
        schema: ArgSchema::Empty,
    },
    ToolSpec {
        name: "get_weather",
        category: "学生情報・その他",
        signature: "get_weather()",
        purpose: "今日と明日の天気(西宮キャンパス)",
        schema: ArgSchema::Empty,
    },
    ToolSpec {
        name: "get_weekly_summary",
        category: "学生情報・その他",
        signature: "get_weekly_summary()",
        purpose: "AI生成済みの週間サマリー・来週の準備事項",
        schema: ArgSchema::Empty,
    },
    ToolSpec {
        name: "get_todo_guide",
        category: "課題・成績・履修",
        signature: "get_todo_guide()",
        purpose: "AI生成のタスクガイド・学習ヒント・3日間の計画",
        schema: ArgSchema::Empty,
    },
    ToolSpec {
        name: "get_upcoming_deadlines",
        category: "課題・成績・履修",
        signature: "get_upcoming_deadlines()",
        purpose: "全科目の締め切り間近のレポート・テスト(着手状況付き)",
        schema: ArgSchema::Empty,
    },
    ToolSpec {
        name: "get_luna_activity_detail",
        category: "課題・成績・履修",
        signature: "get_luna_activity_detail(title: string, activity_type?: string, luna_id?: string)",
        purpose: "タイトル、種別、luna_id等でレポート/テスト/掲示/お知らせの本文・提出要件・添付を取得",
        schema: ArgSchema::LunaActivityDetail,
    },
    ToolSpec {
        name: "refresh_data",
        category: "学生情報・その他",
        signature: "refresh_data()",
        purpose: "Lunaの課題・お知らせ・提出状況を強制的に最新化(数秒かかる)",
        schema: ArgSchema::Empty,
    },
    ToolSpec {
        name: "list_downloaded_files",
        category: "ダウンロードファイル",
        signature: "list_downloaded_files(limit?: number, keyword?: string)",
        purpose: "ダウンロードフォルダ内の最近のファイルを検索・一覧表示",
        schema: ArgSchema::LimitKeyword,
    },
    ToolSpec {
        name: "read_downloaded_file",
        category: "ダウンロードファイル",
        signature: "read_downloaded_file(path?: string, filename?: string)",
        purpose: "ダウンロード済み PDF / DOCX / TXT / MD / JSON / CSV / HTML の本文を抽出して読む。path が不明な場合は filename で検索できる",
        schema: ArgSchema::FilePath,
    },
    ToolSpec {
        name: "write_downloaded_text_file",
        category: "ダウンロードファイル",
        signature: "write_downloaded_text_file(path: string, content: string)",
        purpose: "ダウンロードフォルダ内の .txt / .md / .json / .csv / .html を安全に上書き保存",
        schema: ArgSchema::FileWrite,
    },
    ToolSpec {
        name: "open_downloaded_file",
        category: "ダウンロードファイル",
        signature: "open_downloaded_file(path: string)",
        purpose: "ダウンロード済みファイルをアプリ外部の既定アプリで開く",
        schema: ArgSchema::FilePath,
    },
    ToolSpec {
        name: "delete_downloaded_file",
        category: "ダウンロードファイル",
        signature: "delete_downloaded_file(path: string)",
        purpose: "ダウンロードフォルダ内のファイルを削除する",
        schema: ArgSchema::FilePath,
    },
    ToolSpec {
        name: "download_url",
        category: "ダウンロードファイル",
        signature: "download_url(url: string, filename?: string)",
        purpose: "任意の http(s) URL をダウンロードフォルダに保存する(50MB上限)",
        schema: ArgSchema::DownloadUrl,
    },
    ToolSpec {
        name: "open_luna_attachment",
        category: "ダウンロードファイル",
        signature: "open_luna_attachment(title: string, attachment_name?: string)",
        purpose: "Luna 詳細から添付ファイル/外部資料リンクを探して開く",
        schema: ArgSchema::TitleAttachment,
    },
    ToolSpec {
        name: "download_luna_attachment",
        category: "ダウンロードファイル",
        signature: "download_luna_attachment(title: string, attachment_name?: string, luna_id?: string)",
        purpose: "Luna 詳細から添付ファイル/資料を探してダウンロードする",
        schema: ArgSchema::DownloadLunaAttachment,
    },
    ToolSpec {
        name: "download_course_material",
        category: "ダウンロードファイル",
        signature: "download_course_material(filename: string, title?: string, luna_id?: string)",
        purpose: "指定されたファイル名の授業資料などを自動検索しダウンロードする",
        schema: ArgSchema::DownloadCourseMaterial,
    },
    ToolSpec {
        name: "list_browser_windows",
        category: "ブラウザ",
        signature: "list_browser_windows()",
        purpose: "現在開いているアプリ内ブラウザ一覧",
        schema: ArgSchema::Empty,
    },
    ToolSpec {
        name: "open_browser_url",
        category: "ブラウザ",
        signature: "open_browser_url(url: string)",
        purpose: "URL をアプリ内ブラウザ webview で開く",
        schema: ArgSchema::Url,
    },
    ToolSpec {
        name: "open_copilot_page",
        category: "ブラウザ",
        signature: "open_copilot_page(page: new_tab|files|luna|luna_course|luna_activity|kwic|kwic_notification|kwic_cabinet|kgc|kgc_notification, context?: string, luna_id?: string, identifier?: string)",
        purpose: "SelahのCopilotウィンドウで関連ページを開く。luna_courseはcontextに科目名を渡してその科目のLuna詳細(教材・お知らせ等)を開く。個別活動・通知ページでは検索結果のluna_id/identifierを渡して同名項目を区別する。既知の画面を開く場合はURLを推測せずこちらを使う",
        schema: ArgSchema::CopilotPage,
    },
    ToolSpec {
        name: "read_browser_page",
        category: "ブラウザ",
        signature: "read_browser_page(target?: string)",
        purpose: "ブラウザ webview の主内容・見出し・リンク・操作要素を抽出して読む",
        schema: ArgSchema::OptionalText {
            key: "target",
            max_len: 120,
        },
    },
    ToolSpec {
        name: "browser_back",
        category: "ブラウザ",
        signature: "browser_back(target?: string)",
        purpose: "ブラウザ webview を戻る",
        schema: ArgSchema::OptionalText {
            key: "target",
            max_len: 120,
        },
    },
    ToolSpec {
        name: "browser_forward",
        category: "ブラウザ",
        signature: "browser_forward(target?: string)",
        purpose: "ブラウザ webview を進む",
        schema: ArgSchema::OptionalText {
            key: "target",
            max_len: 120,
        },
    },
    ToolSpec {
        name: "browser_reload_page",
        category: "ブラウザ",
        signature: "browser_reload_page(target?: string)",
        purpose: "ブラウザ webview を再読み込み",
        schema: ArgSchema::OptionalText {
            key: "target",
            max_len: 120,
        },
    },
    ToolSpec {
        name: "browser_click",
        category: "ブラウザ",
        signature: "browser_click(target?: string, text?: string, selector?: string, href_contains?: string, index?: number)",
        purpose: "ページ内のリンク・ボタン・タブなどをクリックする",
        schema: ArgSchema::BrowserClick,
    },
    ToolSpec {
        name: "browser_mouse_click",
        category: "ブラウザ",
        signature: "browser_mouse_click(target?: string, x: number, y: number)",
        purpose: "可視ビューポート内の座標をマウスクリックする。text/label/selectorで届かない時だけ使う",
        schema: ArgSchema::BrowserMouseClick,
    },
    ToolSpec {
        name: "browser_mouse_drag",
        category: "ブラウザ",
        signature: "browser_mouse_drag(target?: string, from_x: number, from_y: number, to_x: number, to_y: number, steps?: number)",
        purpose: "可視ビューポート内でマウスドラッグする。スライダーやキャンバス等の座標操作用",
        schema: ArgSchema::BrowserMouseDrag,
    },
    ToolSpec {
        name: "browser_fill",
        category: "ブラウザ",
        signature: "browser_fill(target?: string, label?: string, selector?: string, value: string, index?: number)",
        purpose: "ページ内の入力欄・テキスト欄に値を入力する",
        schema: ArgSchema::BrowserFill,
    },
    ToolSpec {
        name: "browser_select_option",
        category: "ブラウザ",
        signature: "browser_select_option(target?: string, label?: string, selector?: string, value: string, index?: number)",
        purpose: "ページ内の select / プルダウンで選択する",
        schema: ArgSchema::BrowserSelect,
    },
    ToolSpec {
        name: "browser_press",
        category: "ブラウザ",
        signature: "browser_press(target?: string, key: string, selector?: string)",
        purpose: "ページまたは特定要素へ Enter / Tab などのキー入力を送る",
        schema: ArgSchema::BrowserPress,
    },
    ToolSpec {
        name: "browser_scroll",
        category: "ブラウザ",
        signature: "browser_scroll(target?: string, direction?: up|down|top|bottom, amount?: number, selector?: string)",
        purpose: "ページをスクロール、または要素位置へ移動する",
        schema: ArgSchema::BrowserScroll,
    },
    ToolSpec {
        name: "browser_wait_for",
        category: "ブラウザ",
        signature: "browser_wait_for(target?: string, text?: string, selector?: string, timeout_ms?: number)",
        purpose: "指定したテキストや要素が出るまで少し待つ",
        schema: ArgSchema::BrowserWait,
    },
    ToolSpec {
        name: "browser_close",
        category: "ブラウザ",
        signature: "browser_close(target?: string)",
        purpose: "アプリ内ブラウザのウィンドウを閉じる",
        schema: ArgSchema::OptionalText {
            key: "target",
            max_len: 120,
        },
    },
    ToolSpec {
        name: "computer_screenshot",
        category: "コンピュータ操作",
        signature: "computer_screenshot(target?: string)",
        purpose: "対象ウィンドウを実際のPNGスクリーンショットとして取得する",
        schema: ArgSchema::ComputerScreenshot,
    },
    ToolSpec {
        name: "computer_mouse_click",
        category: "コンピュータ操作",
        signature: "computer_mouse_click(target?: string, x: number, y: number, coordinate_space?: screenshot|screen|webview|viewport)",
        purpose: "実際のOSマウスイベントで指定座標をクリックする",
        schema: ArgSchema::ComputerMouseClick,
    },
    ToolSpec {
        name: "computer_mouse_drag",
        category: "コンピュータ操作",
        signature: "computer_mouse_drag(target?: string, from_x: number, from_y: number, to_x: number, to_y: number, steps?: number, coordinate_space?: screenshot|screen|webview|viewport)",
        purpose: "実際のOSマウスイベントで指定座標間をドラッグする",
        schema: ArgSchema::ComputerMouseDrag,
    },
    ToolSpec {
        name: "computer_scroll",
        category: "コンピュータ操作",
        signature: "computer_scroll(target?: string, delta_y: number, x?: number, y?: number, coordinate_space?: screenshot|screen|webview|viewport)",
        purpose: "実際のOSスクロールイベントを送る。target指定時は対象ウィンドウ中央へマウスを移してからスクロールする",
        schema: ArgSchema::ComputerScroll,
    },
    ToolSpec {
        name: "get_today_brief",
        category: "学生情報・その他",
        signature: "get_today_brief()",
        purpose: "今日の授業・差し迫った締切・天気をまとめて取得",
        schema: ArgSchema::Empty,
    },
    ToolSpec {
        name: "create_google_calendar_event",
        category: "Google Calendar",
        signature: "create_google_calendar_event(title: string, date: string, start_time: string, end_time: string, location?: string, description?: string)",
        purpose: "Google Calendarに単発イベントを追加する。date=YYYY-MM-DD, start_time/end_time=HH:MM。Google連携が必要。",
        schema: ArgSchema::CalendarEvent,
    },
    ToolSpec {
        name: "list_google_calendar_events",
        category: "Google Calendar",
        signature: "list_google_calendar_events()",
        purpose: "予定を返す。events=Agentが登録したイベント(event_id付き、編集・削除前に呼ぶ)、upcoming_events=Selah専用カレンダー上の今後の実際の予定(時間割同期分含む、読み取り専用)。",
        schema: ArgSchema::Empty,
    },
    ToolSpec {
        name: "delete_google_calendar_event",
        category: "Google Calendar",
        signature: "delete_google_calendar_event(event_id: string)",
        purpose: "Agentが登録したGoogle Calendarイベントをevent_idで削除する。",
        schema: ArgSchema::CalendarEventId,
    },
    ToolSpec {
        name: "update_google_calendar_event",
        category: "Google Calendar",
        signature: "update_google_calendar_event(event_id: string, title?: string, date?: string, start_time?: string, end_time?: string, location?: string, description?: string)",
        purpose: "Agentが登録したGoogle Calendarイベントを編集する。event_id必須、他は変更したフィールドのみ指定。",
        schema: ArgSchema::CalendarUpdate,
    },
];
